---
name: Acme-Magic-Pony
version: 0.03
author:
  - 'Jeff Lavallee <jeff@zeroclue.com>'
abstract: Schwern asked for a Magic Pony!
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  CPAN: '>= 1.93'
build_requires:
  Test::More: 0
provides:
  Acme::Magic::Pony:
    file: lib/Acme/Magic/Pony.pm
    version: 0.03
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
